### ISSUE TITLE
Please check your "basic math operation" divide.

### ISSUE THREAD

**Issue by cnguyen1209** [ece-231l-fall-2019/week-4-complex-cong-nguyen-monday-lab#13]
Hi @SteelMatrix ,
May you check your divide code? I try to test but it always return 0+0i. Maybe I wrong but please check it.
Thank you,
@cnguyen1209

**Comment by SteelMatrix** [comment]
Hello @cnguyen1209,
Division works for me on my machine. You have to be careful which values to choose, because it can return very small values. Try the following lines of code:

Complex num(5, 25);
Complex den(5, 0);
Complex ans(1, 5);
Assert(num/den == ans, "real constructor");

With this code, you divide "num" by "den". If you manually calculate it out, or use a calculator, you will get the answer "ans". Feel free to try out different numbers.
@SteelMatrix

**Comment by cnguyen1209** [comment]
@SteelMatrix 
That example work on my machine.
But when I try this tests, it does not work. 
	Complex num(6, 3);
	Complex den(0, 5);
	Complex ans(-0.6, 1.2);
	std::cout << num/den << std::endl;
	Assert(num/den == ans, "real constructor");
I also try to return the value of (num/ den) equal 0+i but correct answer is -3/5 + (6/5)i

**Comment by SteelMatrix** [comment]
Good evening @cnguyen1209,
Plugging this in to my calculator, the result returns 0.6 - 1.2i, so the answer in code would be as below:

Complex ans(0.6, -1.2);

I will go back and check over my math to ensure that it is doing the correct operation.
Wishing the best,
@SteelMatrix

**Comment by cnguyen1209** [comment]
Hi @SteelMatrix ,
Oh. Sorry about that wrong calculation, I see wrong number in my calculator.
Best,
Cong

**Comment by SteelMatrix** [comment]
Glad to see it resolved!
Wishing best,
@SteelMatrix
